export const ADD="ADD";
export const REDUCE="REDUCE";

//TOdos;
export const TODO_REQUEST="TODO_GET_REQUEST";
export const TODO_FAILURE="TODO_GET_FAILURE";

export const TODO_GET_SUCCESS="TODO_GET_SUCCESS";
export const TODO_POST_SUCCESS="TODO_POST_SUCCESS";

export const LOGIN_SUCCESS="LOGIN_SUCCESS";